---
# Main playbook for homelab configuration

- name: Configure base system for all nodes
  hosts: all
  become: true
  tags: ["base"]
  roles:
    - role: security
    - role: ufw
    - role: fail2ban
    - role: node_exporter
      when: node_exporter_enabled | default(true)

- name: Configure high-resource nodes
  hosts: high_resource
  become: true
  tags: ["high"]
  roles:
    - role: prometheus
      when: not prometheus_disabled | default(false)
    - role: grafana
      when: not grafana_disabled | default(false)
    - role: loki
    - role: ollama
    - role: librechat
    - role: jitsi
    - role: whodb

- name: Configure medium-resource nodes
  hosts: medium_resource
  become: true
  tags: ["medium"]
  roles:
    - role: syncthing
    - role: rustdesk
    - role: coolify
      when: coolify_enabled | default(false)
    - role: matrix
    - role: vaultwarden
    - role: n8n

- name: Configure low-resource nodes
  hosts: low_resource
  become: true
  tags: ["low"]
  roles:
    - role: traefik
    - role: hickory_dns
    - role: authelia

- name: Verify all services
  hosts: all
  become: true
  tags: ["verify"]
  pre_tasks:
    - name: Run system verification
      include_role:
        name: verify
      tags: ["always"]
  
  tasks:
    - name: Include service verification
      include_role:
        name: "{{ item }}"
        tasks_from: verify.yml
      loop: "{{ services | default([]) }}"
      when: services is defined
      register: verification_results
      ignore_errors: yes

    - name: Display verification results
      debug:
        var: verification_results
        verbosity: 1

    - name: Check verification reports
      command: "cat /var/log/homelab/verification_{{ inventory_hostname }}.log"
      register: verification_report
      changed_when: false

    - name: Display verification report
      debug:
        msg: "{{ verification_report.stdout_lines }}"

    - name: Check overall verification status
      assert:
        that: 
          - "verification_results.results | map(attribute='failed') | select | list | length == 0"
          - "verification_report.rc == 0"
        msg: "Verification failed. Please check the verification report for details."
      when: verification_results.results is defined
