---
# Main playbook for homelab configuration

- name: Configure base system for all nodes
  hosts: all
  become: true
  tags: ["base"]
  roles:
    - role: security
    - role: ufw
    - role: fail2ban
    - role: node_exporter
      when: node_exporter_enabled | default(true)

- name: Configure high-resource nodes
  hosts: high_resource
  become: true
  tags: ["high"]
  roles:
    - role: prometheus
      when: not prometheus_disabled | default(false)
    - role: grafana
      when: not grafana_disabled | default(false)
    - role: loki
    - role: ollama
    - role: librechat
    - role: jitsi
    - role: whodb

- name: Configure medium-resource nodes
  hosts: medium_resource
  become: true
  tags: ["medium"]
  roles:
    - role: syncthing
    - role: rustdesk
    - role: coolify
      when: coolify_enabled | default(false)
    - role: matrix
    - role: vaultwarden
    - role: n8n

- name: Configure low-resource nodes
  hosts: low_resource
  become: true
  tags: ["low"]
  roles:
    - role: traefik
    - role: hickory_dns
    - role: authelia

- name: Verify all services
  hosts: all
  become: true
  tags: ["verify"]
  tasks:
    - name: Include service verification
      include_role:
        name: "{{ item }}"
        tasks_from: main.yml
      loop: "{{ services | default([]) }}"
      when: services is defined
      register: verification_results
      ignore_errors: yes

    - name: Display verification results
      debug:
        msg: "Service {{ item.item }} verification {{ 'succeeded' if item.role_verified else 'failed' }}"
      loop: "{{ verification_results.results }}"
      when: verification_results.results is defined

    - name: Check overall verification status
      assert:
        that: "verification_results.results | map(attribute='role_verified') | select | list | length == verification_results.results | length"
        msg: "Some service verifications failed. Please check the results above."
      when: verification_results.results is defined
