---
# Ensure Homebrew is up to date
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_ENV_HINTS: 1
  when: is_macos
  tags: ['apps']

# Mac App Store Applications
- name: Check if Mac App Store apps exist in Applications
  stat:
    path: "/Applications/{{ item.name }}.app"
  with_items: "{{ macos_mas_apps }}"
  register: mas_app_check
  when: is_macos
  no_log: "{{ not ansible_verbosity | bool }}"
  tags: ['apps']

- name: Check Mac App Store registration
  shell: "mas list | grep -w '{{ item.item.id }}' || true"
  register: mas_reg_check
  changed_when: false
  with_items: "{{ mas_app_check.results }}"
  when: is_macos and not item.stat.exists
  no_log: "{{ not ansible_verbosity | bool }}"
  tags: ['apps']

- name: Install Mac App Store applications
  community.general.mas:
    id: "{{ item.item.item.id }}"
    state: present
  with_items: "{{ mas_reg_check.results }}"
  when: is_macos and not ansible_check_mode and item.stdout == ''
  no_log: "{{ not ansible_verbosity | bool }}"
  ignore_errors: yes
  tags: ['apps']

# Ensure config directories exist
- name: Ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/.config/personal/cursor"
    - "~/.config/personal/zed"
    - "~/.config/personal/windsurf"
    - "~/.config/personal/pulsar"
    - "~/.config/personal/logseq"
  when: is_macos
  tags: ['apps']

# Copy application templates
- name: Copy application templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: "cursor/settings.json.j2", dest: "~/.config/personal/cursor/settings.json" }
    - { src: "zed/settings.json.j2", dest: "~/.config/personal/zed/settings.json" }
    - { src: "windsurf/settings.json.j2", dest: "~/.config/personal/windsurf/settings.json" }
    - { src: "pulsar/config.cson.j2", dest: "~/.config/personal/pulsar/config.cson" }
    - { src: "logseq/config.edn.j2", dest: "~/.config/personal/logseq/config.edn" }
  when: is_macos
  tags: ['apps']

# Create symlinks for application configs
- name: Create symlinks for application configs
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "~/.config/personal/cursor/settings.json", dest: "~/Library/Application Support/Cursor/User/settings.json" }
    - { src: "~/.config/personal/zed/settings.json", dest: "~/Library/Application Support/Zed/settings/settings.json" }
    - { src: "~/.config/personal/windsurf/settings.json", dest: "~/Library/Application Support/Windsurf/config/settings.json" }
    - { src: "~/.config/personal/pulsar/config.cson", dest: "~/.pulsar/config.cson" }
    - { src: "~/.config/personal/logseq/config.edn", dest: "~/.logseq/config.edn" }
  when: is_macos
  tags: ['apps']

# Homebrew Cask Applications
- name: Check if Homebrew cask apps are installed
  stat:
    path: "/Applications/{{ item.name }}.app"
  register: app_check
  with_items: "{{ macos_apps | selectattr('brew', 'defined') | list }}"
  when: is_macos
  tags: ['apps']

- name: Install desktop applications via Homebrew
  community.general.homebrew_cask:
    name: "{{ item.item.brew }}"
    state: present
    greedy: true
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_ENV_HINTS: 1
  with_items: "{{ app_check.results }}"
  when: is_macos and not item.stat.exists and not ansible_check_mode
  failed_when: false
  ignore_errors: yes
  tags: ['apps']

# Direct Download Applications
- name: Display manual installation instructions for direct download applications
  debug:
    msg: "Please manually install {{ item.name }} from {{ item.url }}"
  with_items: "{{ macos_apps | selectattr('url', 'defined') | list }}"
  when: is_macos
  tags: ['apps']

# CLI Tools Installation
- name: Check if CLI tools are installed
  command: "brew list --formula {{ item }}"
  register: cli_check
  changed_when: false
  failed_when: false
  with_items:
    - thefuck
    - starship
    - zoxide
    - atuin
    - bun
    - aichat
    - ollama
    - jan
    - m-cli
    - terraform
    - kubectl
    - kubectx
    - k9s
    - helm
    - aws-cli
    - azure-cli
    - google-cloud-sdk
    - jq
    - yq
    - ripgrep
    - fd
    - bat
    - eza
    - tmux
    - direnv
    - vim
    - git
    - colima
    - podman
  when: is_macos
  tags: ['cli']

- name: Install CLI tools via Homebrew
  community.general.homebrew:
    name: "{{ item.item }}"
    state: present
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_ENV_HINTS: 1
  with_items: "{{ cli_check.results }}"
  when: is_macos and item.rc != 0 and not ansible_check_mode
  tags: ['cli']

# Linux Applications
- name: Check if Linux applications are installed
  shell: "dpkg -l | grep -w '^ii.*{{ item }}' || true"
  register: linux_check
  changed_when: false
  with_items:
    - podman
    - chromium-browser
    - obs-studio
    - vim
    - git
    - terraform
    - kubectl
    - helm
    - jq
    - yq
    - ripgrep
    - fd-find
    - bat
    - eza
    - tmux
    - direnv
  when: is_linux
  tags: ['apps']

- name: Install Linux applications
  apt:
    name: "{{ item.item }}"
    state: present
  with_items: "{{ linux_check.results }}"
  when: is_linux and item.stdout == ''
  become: true
  tags: ['apps']

# Docker installation for Linux
- name: Check if Docker is installed
  shell: "docker --version || true"
  register: docker_check
  changed_when: false
  when: is_linux
  tags: ['apps']

- name: Install Docker on Linux
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        
    - name: Install Docker packages
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
  when: is_linux and docker_check.rc != 0
  become: true
  tags: ['apps']

# Ensure proper permissions for Docker socket
- name: Ensure Docker socket permissions
  file:
    path: /var/run/docker.sock
    mode: '0666'
  become: true
  when: is_macos
  ignore_errors: yes
  tags: ['apps']

# Configure Colima (Docker alternative)
- name: Check Colima status
  shell: "colima status || true"
  register: colima_check
  changed_when: false
  when: is_macos
  tags: ['apps']

- name: Configure Colima
  shell: |
    colima stop || true
    colima start --cpu 4 --memory 8 --disk 100
  when: is_macos and colima_check.rc != 0
  changed_when: false
  tags: ['apps']

# Post-installation checks
- name: Verify installations
  shell: "{{ item }}"
  register: check_result
  changed_when: false
  failed_when: false
  with_items:
    - "docker --version"
    - "colima status"
    - "podman --version"
    - "zed --version"
    - "cursor --version"
    - "vlc --version"
  when: is_macos
  tags: ['apps']

- name: Display installation results
  debug:
    var: check_result
  when: is_macos
  tags: ['apps']

# WSL specific setup
- name: Configure WSL specific tools
  block:
    - name: Install WSL tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wslu  # WSL utilities
  when: is_wsl
  become: true
  tags: ['wsl']

# Python tools
- name: Install Python tools
  pip:
    name: "{{ item }}"
    state: present
    extra_args: --user
  with_items:
    - thefuck
    - aichat
    - sherlock
  when: not is_macos
  tags: ['python']

# Shell tools for non-MacOS
- name: Install shell tools on Linux
  block:
    - name: Install Starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
      
    - name: Install Zoxide
      shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
      
    - name: Install Atuin
      shell: bash <(curl https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh)
      
    - name: Install Bun
      shell: curl -fsSL https://bun.sh/install | bash
  when: not is_macos
  tags: ['shell']

# Configure AI tools
- name: Pull llama3.2 3B model for ollama
  shell: "ollama pull llama3.2:3b -q"
  register: ollama_pull
  changed_when: ollama_pull.rc == 0
  failed_when: false
  when: is_macos
  tags: ['apps']

- name: Configure aichat to use ollama's llama3.2
  copy:
    dest: "~/.config/aichat/config.yaml"
    content: |
      # aichat configuration
      model: llama3.2
      provider: ollama
      api_base: http://localhost:11434/api
    mode: '0600'
  when: is_macos
  tags: ['apps']

# Zsh plugins
- name: Check if Zsh plugins exist
  stat:
    path: "{{ oh_my_zsh_custom }}/plugins/{{ item.name }}"
  with_items: "{{ zsh_plugins }}"
  register: zsh_plugins_check
  no_log: "{{ not ansible_verbosity | bool }}"
  tags: ['zsh']

- name: Install Zsh plugins
  git:
    repo: "{{ item.item.repo }}"
    dest: "{{ oh_my_zsh_custom }}/plugins/{{ item.item.name }}"
    depth: 1
  with_items: "{{ zsh_plugins_check.results }}"
  when: not item.stat.exists
  no_log: "{{ not ansible_verbosity | bool }}"
  tags: ['zsh']

# SSH Keys
- name: Add private SSH keys to agent
  copy:
    content: "{{ item.key }}"
    dest: "~/.ssh/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items: "{{ ssh_keys }}"
  no_log: true
  tags: ['ssh']
