---
- name: Configure AWS
  block:
    - name: Ensure AWS config directory exists
      file:
        path: "~/.aws"
        state: directory
        mode: '0700'

    - name: Create AWS config file
      template:
        src: aws_config.j2
        dest: ~/.aws/config
        mode: '0600'
        backup: yes
      when: aws_profiles is defined

    - name: Create AWS credentials file
      template:
        src: aws_credentials.j2
        dest: ~/.aws/credentials
        mode: '0600'
        backup: yes
      when: aws_credentials is defined
  when: aws_profiles is defined or aws_credentials is defined
  tags: ['aws']
