---
- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item.brew }}"
    state: present
  with_items: "{{ macos_apps }}"
  when: item.brew is defined
  tags: ['apps']

- name: Install Mac App Store applications
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  with_items: "{{ macos_apps }}"
  when: item.id is defined
  tags: ['apps']

- name: Download and install direct download applications
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.dmg"
  with_items: "{{ macos_apps }}"
  when: item.url is defined
  tags: ['apps']

- name: Mount DMG files
  command: "hdiutil attach /tmp/{{ item.name }}.dmg"
  with_items: "{{ macos_apps }}"
  when: item.url is defined
  tags: ['apps']

- name: Copy applications to Applications folder
  command: "cp -R /Volumes/{{ item.name }}/{{ item.name }}.app /Applications/"
  with_items: "{{ macos_apps }}"
  when: item.url is defined
  tags: ['apps']

- name: Unmount DMG files
  command: "hdiutil detach /Volumes/{{ item.name }}"
  with_items: "{{ macos_apps }}"
  when: item.url is defined
  tags: ['apps']

- name: Clean up DMG files
  file:
    path: "/tmp/{{ item.name }}.dmg"
    state: absent
  with_items: "{{ macos_apps }}"
  when: item.url is defined
  tags: ['apps']
