---
# Check CLI tools
- name: Check if CLI tools are installed
  command: "brew list --formula {{ item.name }}"
  register: cli_check
  changed_when: false
  failed_when: false
  no_log: true
  loop: "{{ cli_tools }}"
  loop_control:
    label: "{{ item.name }}"
  tags: ['devops']

- name: Install CLI tools
  community.general.homebrew:
    name: "{{ item.item.packages }}"
    state: present
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_ENV_HINTS: 1
  loop: "{{ cli_check.results }}"
  when: is_macos and item.rc != 0 and not ansible_check_mode
  loop_control:
    label: "{{ item.item.name }}"
  tags: ['devops']
