---
- name: Check if dotfiles directory exists
  stat:
    path: "{{ '~/dotfiles' | expanduser }}"
  register: dotfiles_stat
  no_log: true
  tags: ['dotfiles']

- name: Ensure dotfiles directory exists
  file:
    path: "{{ '~/dotfiles' | expanduser }}"
    state: directory
    mode: '0755'
  when: not dotfiles_stat.stat.exists
  tags: ['dotfiles']

- name: Check if dotfiles git repo exists
  stat:
    path: "{{ '~/dotfiles/.git' | expanduser }}"
  register: dotfiles_git_stat
  no_log: true
  tags: ['dotfiles']

- name: Initialize dotfiles git repository if not exists
  command: git init
  args:
    chdir: "{{ '~/dotfiles' | expanduser }}"
  when: not dotfiles_git_stat.stat.exists
  tags: ['dotfiles']

- name: Configure dotfiles remote
  command: git remote add origin {{ dotfiles_repo }}
  args:
    chdir: "{{ '~/dotfiles' | expanduser }}"
  register: add_remote
  failed_when: add_remote.rc != 0 and "remote origin already exists" not in add_remote.stderr
  changed_when: add_remote.rc == 0
  tags: ['dotfiles']

- name: Check existing dotfiles
  stat:
    path: "{{ '~/dotfiles' | expanduser }}/{{ item.dest }}"
  register: "existing_dotfiles"
  with_items:
    - { src: "templates/inputrc.j2", dest: ".inputrc" }
    - { src: "templates/zshrc.j2", dest: ".zshrc" }
    - { src: "templates/gitconfig.j2", dest: ".gitconfig" }
    - { src: "templates/gitconfig-provisions.j2", dest: ".gitconfig-provisions" }
  no_log: true
  loop_control:
    label: "{{ item.dest }}"
  tags: ['dotfiles']

- name: Copy dotfiles
  template:
    src: "{{ item.item.src }}"
    dest: "{{ '~/dotfiles' | expanduser }}/{{ item.item.dest }}"
    mode: '0644'
    backup: yes
    force: no
  when: not item.stat.exists
  loop: "{{ existing_dotfiles.results }}"
  tags: ['dotfiles']

- name: Check git hooks directory
  stat:
    path: "{{ '~/dotfiles/.git/hooks' | expanduser }}"
  register: hooks_stat
  tags: ['dotfiles']

- name: Create git hooks directory
  file:
    path: "{{ '~/dotfiles/.git/hooks' | expanduser }}"
    state: directory
    mode: '0755'
  when: not hooks_stat.stat.exists
  tags: ['dotfiles']

- name: Check post-commit hook
  stat:
    path: "{{ '~/dotfiles/.git/hooks/post-commit' | expanduser }}"
  register: post_commit_stat
  tags: ['dotfiles']

- name: Install post-commit hook
  template:
    src: post-commit.j2
    dest: "{{ '~/dotfiles/.git/hooks/post-commit' | expanduser }}"
    mode: '0755'
    backup: yes
    force: no
  when: not post_commit_stat.stat.exists
  tags: ['dotfiles']

- name: Check existing symlinks
  stat:
    path: "~/{{ item.dest }}"
  register: "existing_symlinks"
  with_items:
    - .inputrc
    - .zshrc
    - .gitconfig
    - .gitconfig-provisions
  tags: ['dotfiles']

- name: Create symlinks
  file:
    src: "{{ '~/dotfiles' | expanduser }}/{{ item.item.dest }}"
    dest: "~/{{ item.item.dest }}"
    state: link
    force: no
  loop: "{{ existing_symlinks.results }}"
  when: not item.stat.exists
  tags: ['dotfiles']

- name: Configure git for dotfiles
  blockinfile:
    path: "{{ '~/dotfiles/.git/config' | expanduser }}"
    block: |
      [core]
        autocrlf = input
        filemode = true
      [push]
        default = current
      [pull]
        rebase = true
    create: yes
  tags: ['dotfiles']

- name: Create initial commit if repository is empty
  shell: |
    if [ -z "$(git log -1 2>/dev/null)" ]; then
      git add .
      git commit -m "Initial dotfiles setup"
    fi
  args:
    chdir: "{{ '~/dotfiles' | expanduser }}"
  tags: ['dotfiles']
