---
# Directory setup
- name: Ensure Git directories exist
  file:
    path: "{{ item | expanduser }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ git_base_dir }}"
    - "{{ devenv_dir }}"
    - "~/.config/git"
    - "~/.config/git/includes"
  loop_control:
    label: "{{ item | basename }}"
  tags: ['git']

# Git configuration
- name: Configure git globally
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: 'user.name', value: '{{ git_user_name | default("l3ocifer") }}' }
    - { name: 'user.email', value: '{{ git_user_email | default("lpask001@gmail.com") }}' }
    - { name: 'http.postBuffer', value: '524288000' }
    - { name: 'credential.helper', value: 'cache --timeout=604800' }
    - { name: 'core.autocrlf', value: 'input' }
    - { name: 'core.longpaths', value: 'true' }
    - { name: 'pull.rebase', value: 'true' }
  loop_control:
    label: "{{ item.name }}"
  tags: ['git']

# Configure Git SSH command
- name: Check for SSH keys in secrets
  set_fact:
    available_ssh_keys: "{{ ssh_keys | default([]) | map(attribute='name') | list }}"
  tags: ['git']

- name: Configure Git SSH command
  git_config:
    name: core.sshCommand
    scope: global
    value: >-
      ssh -i {{ '~/.ssh/leo-personal' | expanduser }}
      {% for key in ssh_keys | default([]) %}
      {% if key.name != 'leo-personal' %}
      -i {{ '~/.ssh/' ~ key.name | expanduser }}
      {% endif %}
      {% endfor %}
      -o IdentitiesOnly=yes
  when: "'leo-personal' in available_ssh_keys"
  tags: ['git']

# Client-specific git configurations
- name: Create client-specific git configs
  template:
    src: "gitconfig-client.j2"
    dest: "{{ '~/.config/git/includes/gitconfig-' | expanduser }}{{ item.name }}"
    mode: '0644'
    backup: yes
    force: no
  loop: "{{ git_client_configs | default([]) }}"
  tags: ['git']

# Clone repositories
- name: Clone or update devenv repository
  git:
    repo: "{{ repositories.devenv.repo }}"
    dest: "{{ repositories.devenv.dest | expanduser }}"
    update: yes
    force: no
  tags: ['git']

- name: Clone or update scripts repository
  git:
    repo: "{{ repositories.scripts.repo }}"
    dest: "{{ repositories.scripts.dest | expanduser }}"
    update: yes
    force: no
  tags: ['git']
