---
# Rust Installation and Update
- name: Check if Rust is installed
  stat:
    path: "{{ '~/.cargo/bin/rustc' | expanduser }}"
  register: rust_check
  tags: ['languages']
  no_log: true

- name: Install/Update Rust via rustup
  shell: |
    if ! command -v rustup &> /dev/null; then
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    else
      rustup update
    fi
  args:
    creates: "{{ '~/.cargo/bin/rustc' | expanduser }}"
  when: not rust_check.stat.exists
  tags: ['languages']

# Python Setup via Miniconda
- name: Check if Miniconda is installed
  stat:
    path: "{{ '~/miniconda3/bin/conda' | expanduser }}"
  register: conda_check
  tags: ['languages']
  no_log: true

- name: Install miniconda
  block:
    - name: Download miniconda installer
      get_url:
        url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-{{ 'MacOSX' if is_macos else 'Linux' }}-{{ 'arm64' if ansible_architecture == 'arm64' else 'x86_64' }}.sh"
        dest: "/tmp/miniconda.sh"
        mode: '0755'
      when: not conda_check.stat.exists
      tags: ['languages']

    - name: Run miniconda installer
      shell: "/tmp/miniconda.sh -b -p {{ '~/miniconda3' | expanduser }}"
      args:
        creates: "{{ '~/miniconda3/bin/conda' | expanduser }}"
      when: not conda_check.stat.exists
      tags: ['languages']

    - name: Initialize conda
      shell: |
        source {{ '~/miniconda3/bin/activate' | expanduser }}
        conda init zsh
      args:
        executable: /bin/zsh
      when: not conda_check.stat.exists
      tags: ['languages']

# Node.js Setup
- name: Check if nvm is installed
  stat:
    path: "{{ '~/.nvm/nvm.sh' | expanduser }}"
  register: nvm_check
  tags: ['languages']
  no_log: true

- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ '~/.nvm/nvm.sh' | expanduser }}"
  when: not nvm_check.stat.exists
  tags: ['languages']

- name: Install Node.js via nvm
  shell: |
    export NVM_DIR="{{ '~/.nvm' | expanduser }}"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts
  args:
    executable: /bin/bash
  when: not nvm_check.stat.exists
  tags: ['languages']

# Ruby Setup
- name: Setup Ruby
  block:
    - name: Install rbenv on Linux
      package:
        name: rbenv
        state: present
      when: is_linux

    - name: Install rbenv on macOS
      homebrew:
        name: rbenv
        state: present
      when: is_macos
    
    - name: Initialize rbenv
      shell: |
        eval "$(rbenv init -)"
      args:
        executable: /bin/bash
    
    - name: Install Ruby version
      shell: |
        eval "$(rbenv init -)"
        rbenv install {{ languages.ruby.version | default('3.2.0') }} -s
        rbenv global {{ languages.ruby.version | default('3.2.0') }}
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.rbenv/versions/{{ languages.ruby.version | default('3.2.0') }}"
    
    - name: Install Ruby gems
      shell: |
        eval "$(rbenv init -)"
        gem install {{ languages.ruby.gems | default(['bundler', 'rails']) | join(' ') }}
      args:
        executable: /bin/bash
  tags: ['languages']

# Go Setup
- name: Install Go
  package:
    name: golang
    state: present
  become: true
  when: is_linux
  tags: ['languages']

- name: Set GOPATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export GOPATH="{{ ansible_env.HOME }}/go"'
    create: yes
  tags: ['languages']
