---
# Ensure scripts directory exists
- name: Create scripts directory
  file:
    path: "{{ scripts_dir }}"
    state: directory
    mode: '0755'
  tags: ['scripts']

# Clone or update scripts repository
- name: Check if scripts repository exists
  stat:
    path: "{{ scripts_dir }}/.git"
  register: scripts_git
  tags: ['scripts']

- name: Clone scripts repository if not exists
  git:
    repo: "{{ scripts_repo }}"
    dest: "{{ scripts_dir }}"
    version: main
    accept_hostkey: yes
  when: not scripts_git.stat.exists
  tags: ['scripts']

- name: Update scripts repository if exists
  git:
    repo: "{{ scripts_repo }}"
    dest: "{{ scripts_dir }}"
    version: main
    update: yes
  when: scripts_git.stat.exists
  tags: ['scripts']

# Set proper permissions
- name: Set scripts permissions
  file:
    path: "{{ scripts_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags: ['scripts']

# Add scripts to PATH
- name: Ensure scripts directory is in PATH
  lineinfile:
    path: "~/.zshrc"
    line: 'export PATH="{{ scripts_dir }}:$PATH"'
    regexp: '^export PATH="{{ scripts_dir }}'
    create: yes
  tags: ['scripts']
