---
# Ensure scripts directory exists
- name: Create scripts directory
  file:
    path: "{{ scripts_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags: ['scripts']

# Add scripts to PATH
- name: Ensure scripts directory is in PATH
  lineinfile:
    path: "~/.zshrc"
    line: 'export PATH="{{ scripts_dir }}:$PATH"'
    regexp: '^export PATH="{{ scripts_dir }}'
    create: yes
  tags: ['scripts']
