---
# Oh My Zsh setup
- name: Check Oh My Zsh installation
  stat:
    path: "{{ oh_my_zsh_custom }}"
  register: omz_stat
  tags: ['shell']

- name: Clone Oh My Zsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ oh_my_zsh_dir }}"
    version: master
  when: not omz_stat.stat.exists
  tags: ['shell']

- name: Create Oh My Zsh custom directory
  file:
    path: "{{ oh_my_zsh_custom }}"
    state: directory
    mode: '0755'
  when: not omz_stat.stat.exists
  tags: ['shell']

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ oh_my_zsh_custom }}/plugins/zsh-autosuggestions"
    version: master
  when: not omz_stat.stat.exists
  tags: ['shell']

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ oh_my_zsh_custom }}/plugins/zsh-syntax-highlighting"
    version: master
  when: not omz_stat.stat.exists
  tags: ['shell']

- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ oh_my_zsh_custom }}/themes/powerlevel10k"
    version: master
  when: not omz_stat.stat.exists
  tags: ['shell']
