---
# Oh My Zsh setup
- name: Check Oh My Zsh installation
  stat:
    path: "{{ oh_my_zsh_custom }}"
  register: omz_stat
  tags: ['shell']

- name: Install Oh My Zsh and plugins
  block:
    - name: Clone Oh My Zsh
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ oh_my_zsh_dir }}"
        version: master
        depth: 1
      when: not omz_stat.stat.exists

    - name: Create Oh My Zsh custom directory
      file:
        path: "{{ oh_my_zsh_custom }}"
        state: directory
        mode: '0755'
      when: not omz_stat.stat.exists

    - name: Install Oh My Zsh plugins
      git:
        repo: "{{ item.repo }}"
        dest: "{{ oh_my_zsh_custom }}/plugins/{{ item.name }}"
        version: master
        depth: 1
      loop:
        - { name: 'zsh-autosuggestions', repo: 'https://github.com/zsh-users/zsh-autosuggestions' }
        - { name: 'zsh-syntax-highlighting', repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git' }
      when: not omz_stat.stat.exists

    - name: Install powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ oh_my_zsh_custom }}/themes/powerlevel10k"
        version: master
        depth: 1
      when: not omz_stat.stat.exists

    - name: Verify Oh My Zsh installation
      stat:
        path: "{{ oh_my_zsh_dir }}/.git"
      register: omz_verify
      failed_when: not omz_verify.stat.exists
  rescue:
    - name: Handle Oh My Zsh installation failure
      debug:
        msg: "Failed to install Oh My Zsh. Please check your internet connection and try again."
  tags: ['shell']
