---
- name: Create shell configuration files
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/zsh/{{ item }}"
    mode: '0644'
  with_items:
    - aliases
    - exports
  tags: ['shell']

- name: Configure .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: '0644'
  tags: ['shell']

- name: Install Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
  tags: ['shell']

- name: Install Zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  with_items:
    - { name: zsh-autosuggestions, repo: https://github.com/zsh-users/zsh-autosuggestions.git }
    - { name: zsh-syntax-highlighting, repo: https://github.com/zsh-users/zsh-syntax-highlighting.git }
  tags: ['shell']
