---
- name: Ensure SSH directory exists with correct permissions
  file:
    path: "{{ ssh_config_dir | expanduser }}"
    state: directory
    mode: '0700'
  tags: ['ssh']

- name: Copy SSH configuration
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_dir | expanduser }}/config"
    mode: '0600'
    backup: yes
  when: ansible_os_family == 'Darwin'
  tags: ['ssh']

- name: Check existing SSH keys
  ansible.builtin.stat:
    path: "~/.ssh/{{ item.name }}"
  loop: "{{ ssh_keys }}"
  register: ssh_key_check
  no_log: true
  tags: ['ssh']

- name: Add SSH keys if missing
  ansible.builtin.copy:
    content: "{{ item.item.key }}"
    dest: "~/.ssh/{{ item.item.name }}"
    mode: "{{ item.item.mode }}"
    force: false
    backup: false
  loop: "{{ ssh_key_check.results }}"
  when: not item.stat.exists
  register: ssh_key_add
  no_log: true
  changed_when: not item.stat.exists
  tags: ['ssh']

- name: Display SSH key status
  ansible.builtin.debug:
    verbosity: 1
    msg: "SSH key {{ item.item.name }} {{ 'added' if not item.stat.exists else 'exists' }}"
  loop: "{{ ssh_key_check.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  tags: ['ssh']

- name: Start SSH agent
  shell: |
    if ! pgrep -u $USER ssh-agent > /dev/null; then
      eval $(ssh-agent -s)
    fi
  register: ssh_agent_start
  changed_when: false
  tags: ['ssh']

# Only add private keys (mode 0600) to the SSH agent, public keys are filtered out
- name: Add private SSH keys to agent (mode 0600 only)
  shell: |
    if ! ssh-add -l | grep -q "{{ item.name }}"; then
      ssh-add {{ ssh_config_dir | expanduser }}/{{ item.name }}
    fi
  loop: "{{ ssh_keys | default([]) | selectattr('mode', 'equalto', '0600') | list }}"
  when: ssh_keys | length > 0
  no_log: true
  changed_when: false
  register: ssh_key_agent_add
  tags: ['ssh']

- name: Display SSH key agent status
  ansible.builtin.debug:
    verbosity: 1
    msg: "SSH key {{ item.item.name }} {{ 'added to agent' if item.rc == 0 else 'already in agent' }}"
  loop: "{{ ssh_key_agent_add.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  tags: ['ssh']
