---
- name: Ensure SSH directory exists with correct permissions
  file:
    path: "{{ ssh_config_dir | expanduser }}"
    state: directory
    mode: '0700'
  tags: ['ssh']

- name: Copy SSH configuration
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_dir | expanduser }}/config"
    mode: '0600'
    backup: yes
  when: ansible_os_family == 'Darwin'
  tags: ['ssh']

- name: Copy SSH keys from secrets
  copy:
    content: "{{ item.key }}"
    dest: "{{ ssh_config_dir }}/{{ item.name }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: "{{ ssh_keys | default([]) }}"
  no_log: true
  tags: ['ssh']

- name: Start SSH agent
  shell: |
    if ! pgrep -u $USER ssh-agent > /dev/null; then
      eval $(ssh-agent -s)
    fi
  register: ssh_agent_start
  changed_when: false
  tags: ['ssh']

- name: Add SSH keys to agent
  shell: |
    if ! ssh-add -l | grep -q "{{ item.name }}"; then
      ssh-add {{ ssh_config_dir | expanduser }}/{{ item.name }}
    fi
  with_items: >-
    {{
      ssh_keys | default([]) |
      reject('search', '\.pub$') |
      list
    }}
  when: ssh_keys | length > 0
  tags: ['ssh']
