---
# Install and configure Syncthing
- name: Install Syncthing
  block:
    - name: Install Syncthing (MacOS)
      community.general.homebrew_cask:
        name: syncthing
        state: present
      when: is_macos
      register: syncthing_macos_install
      
    - name: Install Syncthing (Linux)
      block:
        - name: Add Syncthing repository key
          apt_key:
            url: https://syncthing.net/release-key.txt
            state: present
            id: 37C84554E7E0A261E4F76E1ED26E6ED000654A3E
          when: is_wsl
          
        - name: Add Syncthing repository
          apt_repository:
            repo: deb https://apt.syncthing.net/ syncthing stable
            state: present
            filename: syncthing
          when: is_wsl
          
        - name: Install Syncthing package
          apt:
            name: syncthing
            state: present
            update_cache: yes
      when: is_linux
      become: true
      register: syncthing_linux_install
  rescue:
    - name: Handle Syncthing installation failure
      debug:
        msg: "Failed to install Syncthing. Please check system requirements and try again."
  tags: ['syncthing']

# Create required directories
- name: Create Syncthing directories
  file:
    path: "{{ item | expanduser }}"
    state: directory
    mode: '0700'
  with_items:
    - "~/.config/syncthing"
  tags: ['syncthing']

# Configure Syncthing
- name: Update secrets file with Syncthing configuration
  blockinfile:
    path: "{{ secrets_file }}"
    create: yes
    mode: '0600'
    block: |
      syncthing_api_key: "{{ syncthing_api_key | default(lookup('password', '/dev/null chars=ascii_letters,digits length=32')) }}"
      syncthing_secrets_folder_id: "{{ syncthing_secrets_folder_id }}"
      syncthing_scripts_folder_id: "{{ syncthing_scripts_folder_id }}"
      syncthing_ssh_folder_id: "{{ syncthing_ssh_folder_id }}"
  tags: ['syncthing']

- name: Configure Syncthing
  template:
    src: syncthing_config.xml.j2
    dest: ~/.config/syncthing/config.xml
    mode: '0600'
    validate: 'syncthing cli config validate %s'
  register: syncthing_config
  tags: ['syncthing']

# Service Management
- name: Configure Syncthing service
  block:
    - name: Create LaunchAgent directory (MacOS)
      file:
        path: ~/Library/LaunchAgents
        state: directory
        mode: '0755'
      when: is_macos

    - name: Install Syncthing LaunchAgent (MacOS)
      template:
        src: syncthing.plist.j2
        dest: ~/Library/LaunchAgents/net.syncthing.syncthing.plist
        mode: '0644'
        validate: 'plutil -lint %s'
      when: is_macos
      register: launchagent

    - name: Manage Syncthing LaunchAgent (MacOS)
      command: "{{ item }}"
      with_items:
        - launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
        - launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
      when: is_macos and (launchagent.changed or syncthing_config.changed)
      ignore_errors: true

    - name: Start Syncthing service (Linux)
      systemd:
        name: syncthing@{{ ansible_user_id }}
        state: restarted
        enabled: yes
        scope: user
        daemon_reload: yes
      when: is_linux and not is_wsl and (syncthing_config.changed or syncthing_linux_install.changed)
  rescue:
    - name: Handle service configuration failure
      debug:
        msg: "Failed to configure Syncthing service. Please check system logs for details."
  tags: ['syncthing']

# Verify Installation
- name: Verify Syncthing is running
  command: pgrep syncthing
  register: syncthing_check
  changed_when: false
  retries: 3
  delay: 5
  until: syncthing_check.rc == 0
  tags: ['syncthing']
