---
- name: Install Syncthing
  block:
    - name: Install Syncthing (MacOS)
      community.general.homebrew_cask:
        name: syncthing
        state: present
      when: is_macos
      
    - name: Install Syncthing (Linux)
      block:
        - name: Add Syncthing repository key
          apt_key:
            url: https://syncthing.net/release-key.txt
            state: present
          when: is_wsl
          
        - name: Add Syncthing repository
          apt_repository:
            repo: deb https://apt.syncthing.net/ syncthing stable
            state: present
          when: is_wsl
          
        - name: Install Syncthing package
          apt:
            name: syncthing
            state: present
            update_cache: yes
      when: is_linux
      become: true
  tags: ['syncthing']

- name: Create Syncthing directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - "~/.config/syncthing"
    - "~/.secrets"
  tags: ['syncthing']

- name: Update secrets file with Syncthing API key
  blockinfile:
    path: "{{ secrets_file }}"
    create: yes
    mode: '0600'
    block: |
      syncthing_api_key: "{{ syncthing_api_key | default(lookup('password', '/dev/null chars=ascii_letters,digits length=32')) }}"
      syncthing_secrets_folder_id: "{{ syncthing_secrets_folder_id | default(lookup('password', '/dev/null chars=ascii_letters,digits length=32')) }}"
  tags: ['syncthing']

- name: Configure Syncthing
  template:
    src: syncthing_config.xml.j2
    dest: ~/.config/syncthing/config.xml
    mode: '0600'
  tags: ['syncthing']

- name: Configure Syncthing service
  block:
    - name: Create LaunchAgent directory
      file:
        path: ~/Library/LaunchAgents
        state: directory
        mode: '0755'
      when: is_macos

    - name: Install Syncthing LaunchAgent
      template:
        src: syncthing.plist.j2
        dest: ~/Library/LaunchAgents/net.syncthing.syncthing.plist
        mode: '0644'
      when: is_macos
      register: launchagent

    - name: Load Syncthing LaunchAgent
      command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
      when: is_macos and launchagent.changed

    - name: Start Syncthing service
      systemd:
        name: syncthing@{{ ansible_user_id }}
        state: started
        enabled: yes
        scope: user
      when: is_linux and not is_wsl
  tags: ['syncthing']
