---
# Verify directory structure
- name: Verify directories
  stat:
    path: "{{ item }}"
  register: dir_check
  failed_when: not dir_check.stat.exists
  with_items:
    - "{{ git_base_dir }}"
    - "{{ devenv_dir }}"
    - "{{ scripts_dir }}"
    - "~/.config/personal"
    - "~/.config/zsh"
    - "{{ ssh_config_dir }}"
  no_log: true

# Verify git repositories
- name: Verify git repositories
  command: git status
  args:
    chdir: "{{ item }}"
  register: git_check
  changed_when: false
  failed_when: git_check.rc != 0
  with_items:
    - "{{ devenv_dir }}"
    - "{{ scripts_dir }}"

# Verify essential tools
- name: Verify essential tools
  command: "{{ item }}"
  register: tool_check
  changed_when: false
  failed_when: tool_check.rc != 0
  with_items:
    - git --version
    - python3 -c "import sys; assert sys.version_info >= (3, 9), 'Python 3.9+ required'"
    - curl --version
    - zsh --version

# Verify Syncthing
- name: Check Syncthing service status
  shell: |
    pgrep -f syncthing || (launchctl list | grep syncthing)
  register: syncthing_check
  changed_when: false
  failed_when: false

- name: Verify Syncthing configuration
  command: grep -q "folder id=" ~/.config/syncthing/config.xml
  register: syncthing_config
  changed_when: false
  failed_when: syncthing_config.rc != 0

- name: Verify secrets file is being synced
  command: grep -q "folder id=\"{{ syncthing_secrets_folder_id }}\"" ~/.config/syncthing/config.xml
  register: secrets_sync_check
  changed_when: false
  failed_when: secrets_sync_check.rc != 0

# Verify symlinks
- name: Verify configuration symlinks
  stat:
    path: "{{ item.dest | expanduser }}"
  register: symlink_check
  failed_when: not symlink_check.stat.exists or not symlink_check.stat.islnk
  with_items:
    # Shell configs
    - { dest: "~/.zshrc", required: true }
    - { dest: "~/.config/zsh/aliases", required: true }
    - { dest: "~/.config/zsh/exports", required: true }
    # Git configs
    - { dest: "~/.gitconfig", required: true }
    - { dest: "~/.config/git/config", required: true }
    # SSH configs
    - { dest: "~/.ssh/config", required: true }
    # Application configs (optional)
    - { dest: "~/.config/cursor/settings.json", required: false }
    - { dest: "~/.config/zed/settings.json", required: false }
    - { dest: "~/.config/pulsar/config.cson", required: false }
    - { dest: "~/.config/logseq/config.edn", required: false }
  no_log: false
  ignore_errors: "{{ not item.required }}"

# Verify SSH and Git functionality
- name: Test SSH agent
  shell: ssh-add -l
  register: ssh_agent_check
  changed_when: false
  failed_when: ssh_agent_check.rc == 2  # RC=2 means no agent running, RC=1 means no keys but agent running

- name: Test Git SSH access
  shell: ssh -T git@github.com
  register: git_ssh_check
  changed_when: false
  failed_when: git_ssh_check.rc == 255  # RC=1 is normal for successful auth

# Platform-specific verification
- name: Verify macOS specific tools
  command: "{{ item }}"
  register: macos_check
  changed_when: false
  failed_when: macos_check.rc != 0
  with_items:
    - brew --version
    - docker --version
    - colima version
  when: is_macos

- name: Verify Linux specific tools
  command: "{{ item }}"
  register: linux_check
  changed_when: false
  failed_when: linux_check.rc != 0
  with_items:
    - docker --version
    - python3 -m pip --version
  when: is_linux or is_wsl

# Display verification results
- name: Show verification summary
  debug:
    msg: |
      Verification Results:
      - Directories: {{ dir_check.results | map(attribute='stat.exists') | list | all }}
      - Git Repos: {{ git_check.results | map(attribute='rc') | list | all == 0 }}
      - Tools: {{ tool_check.results | map(attribute='rc') | list | all == 0 }}
      - Syncthing: {{ syncthing_config.rc == 0 }}
      - Secrets Sync: {{ secrets_sync_check.rc == 0 }}
      - SSH Agent: {{ ssh_agent_check.rc != 2 }}
      - Git SSH: {{ git_ssh_check.rc != 255 }}
