---
# Verify essential directories and files
- name: Verify essential directories exist
  stat:
    path: "{{ item | expanduser }}"
  register: dir_check
  failed_when: not dir_check.stat.exists
  with_items:
    - "{{ git_base_dir }}"
    - "{{ devenv_dir }}"
    - "{{ scripts_dir }}"
    - "~/.config/personal"
    - "~/.config/git"
    - "~/.config/git/includes"
    - "~/.config/zsh"
    - "~/.config/syncthing"
    - "{{ ssh_config_dir }}"
  no_log: true
  tags: ['verify', 'directories']

- name: Verify essential files exist
  stat:
    path: "{{ item | expanduser }}"
  register: file_check
  failed_when: not file_check.stat.exists
  with_items:
    - "~/.config/personal/.git/config"
    - "~/.config/git/config"
    - "~/.ssh/config"
    - "~/.config/syncthing/config.xml"
    - "~/.zshrc"
  no_log: true
  tags: ['verify', 'files']

- name: Verify Syncthing is running
  command: pgrep syncthing
  register: syncthing_check
  failed_when: syncthing_check.rc != 0
  changed_when: false
  tags: ['verify', 'sync']

- name: Verify SSH agent is running
  command: pgrep ssh-agent
  register: ssh_agent_check
  failed_when: ssh_agent_check.rc != 0
  changed_when: false
  tags: ['verify', 'ssh']

- name: Verify Git configuration
  command: git config --global --get user.email
  register: git_config_check
  failed_when: git_config_check.rc != 0
  changed_when: false
  tags: ['verify', 'git']

- name: Verify Oh My Zsh installation
  stat:
    path: "{{ oh_my_zsh_dir }}"
  register: omz_check
  failed_when: not omz_check.stat.exists
  tags: ['verify', 'shell']

# Display verification results
- name: Display verification summary
  debug:
    msg: |
      Verification Results:
      - Directories: {{ dir_check.results | map(attribute='stat.exists') | list | all }}
      - Files: {{ file_check.results | map(attribute='stat.exists') | list | all }}
      - Syncthing: {{ syncthing_check.rc == 0 }}
      - SSH Agent: {{ ssh_agent_check.rc == 0 }}
      - Git Config: {{ git_config_check.rc == 0 }}
      - Oh My Zsh: {{ omz_check.stat.exists }}
