---
# Verify directory structure
- name: Verify directories
  stat:
    path: "{{ item | expanduser }}"
  register: dir_check
  failed_when: not dir_check.stat.exists
  with_items:
    - "{{ git_base_dir }}"
    - "{{ devenv_dir }}"
    - "{{ scripts_dir }}"
    - "~/.config/personal"
    - "~/.config/zsh"
    - "{{ ssh_config_dir }}"
  no_log: true

# Verify configuration symlinks
- name: Verify configuration symlinks
  stat:
    path: "{{ item.dest | expanduser }}"
  register: symlink_check
  failed_when: >
    item.required and (
      not symlink_check.stat.exists or
      not symlink_check.stat.islnk or
      symlink_check.stat.lnk_source != (item.src | expanduser | realpath)
    )
  with_items: "{{ config_files }}"
  no_log: false

# Verify essential tools
- name: Verify essential tools
  command: "{{ item }}"
  register: tool_check
  changed_when: false
  failed_when: tool_check.rc != 0
  with_items:
    - git --version
    - python3 -c "import sys; assert sys.version_info >= (3, 9), 'Python 3.9+ required'"
    - curl --version
    - zsh --version

# Verify Syncthing
- name: Check Syncthing service status
  shell: |
    {% if ansible_system == 'Darwin' %}
    pgrep -f syncthing || (launchctl list | grep syncthing)
    {% else %}
    systemctl is-active --quiet syncthing@$USER || pgrep -f syncthing
    {% endif %}
  register: syncthing_check
  changed_when: false
  failed_when: false

- name: Verify Syncthing configuration exists
  stat:
    path: "~/.config/syncthing/config.xml"
  register: syncthing_config_check
  failed_when: syncthing_check.rc == 0 and not syncthing_config_check.stat.exists

- name: Verify Syncthing secrets folder
  block:
    - name: Check secrets folder in Syncthing config
      command: grep -q "folder id=\"{{ syncthing_secrets_folder_id }}\"" ~/.config/syncthing/config.xml
      register: secrets_sync_check
      changed_when: false
      failed_when: false

    - name: Verify secrets folder path
      command: grep -q "path=\"{{ secrets_dir | expanduser | realpath }}\"" ~/.config/syncthing/config.xml
      register: secrets_path_check
      changed_when: false
      failed_when: secrets_sync_check.rc == 0 and secrets_path_check.rc != 0
  when: syncthing_check.rc == 0 and syncthing_config_check.stat.exists

# Verify SSH and Git functionality
- name: Test SSH agent
  shell: ssh-add -l
  register: ssh_agent_check
  changed_when: false
  failed_when: ssh_agent_check.rc == 2  # RC=2 means no agent running, RC=1 means no keys but agent running

- name: Test Git SSH access
  shell: ssh -T git@github.com
  register: git_ssh_check
  changed_when: false
  failed_when: git_ssh_check.rc == 255  # RC=1 is normal for successful auth

# Platform-specific verification
- name: Verify macOS specific tools
  command: "{{ item }}"
  register: macos_check
  changed_when: false
  failed_when: macos_check.rc != 0
  with_items:
    - brew --version
    - docker --version
    - colima version
  when: is_macos

- name: Verify Linux specific tools
  command: "{{ item }}"
  register: linux_check
  changed_when: false
  failed_when: linux_check.rc != 0
  with_items:
    - docker --version
    - python3 -m pip --version
  when: is_linux or is_wsl

# Display verification results
- name: Display verification summary
  debug:
    msg: |
      Verification Results:
      - Directories: {{ dir_check.results | map(attribute='stat.exists') | list | all }}
      - Tools: {{ tool_check.results | map(attribute='rc') | list | all == 0 }}
      - Syncthing: {{ syncthing_check.rc == 0 }}
      - Syncthing Config: {{ syncthing_config_check.stat.exists if syncthing_check.rc == 0 else 'N/A' }}
      - Secrets Sync: {{ secrets_sync_check.rc == 0 if syncthing_check.rc == 0 else 'N/A' }}
      - SSH Agent: {{ ssh_agent_check.rc != 2 }}
      - Git SSH: {{ git_ssh_check.rc != 255 }}
