---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: l3o
    ansible_ssh_private_key_file: ~/.ssh/leo-personal

  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
    
    homelab:
      children:
        high_resource:
          hosts:
            alef:
              ansible_host: 192.168.1.10
              ansible_user: admin
              node_type: server
              services:
                - prometheus
                - grafana
                - loki
                - ollama
                - librechat
                - jitsi
        
        medium_resource:
          hosts:
            bet:
              ansible_host: 192.168.1.11
              ansible_user: admin
              node_type: server
              services:
                - syncthing
                - rustdesk
                - coolify
        
            gimel:
              ansible_host: 192.168.1.12
              ansible_user: admin
              node_type: server
              services:
                - matrix
                - vaultwarden
                - n8n
        
        low_resource:
          hosts:
            dalet:
              ansible_host: 192.168.1.13
              ansible_user: admin
              node_type: pi
              services:
                - traefik
                - hickory_dns
                - node_exporter
        
            he:
              ansible_host: 192.168.1.14
              ansible_user: admin
              node_type: pi
              services:
                - authelia
                - fail2ban
                - ufw
        
        main_server:
          hosts:
            alef:
              ansible_host: 192.168.1.200
              ansible_port: 22
              # Server specifications
              ram_gb: 55
              storage_gb: 3000
              cpu_cores: 8
        
        # Distributed services across Pi cluster
        dns_nodes:
          vars:
            dns_role: secondary
            route53_integration: true
          hosts:
            legion001:
              ansible_host: 192.168.1.31
              dns_role: primary
            legion002:
              ansible_host: 192.168.1.32
            legion003:
              ansible_host: 192.168.1.33
            legion004:
              ansible_host: 192.168.1.34
            legion005:
              ansible_host: 192.168.1.35
        
        monitoring_nodes:
          vars:
            node_exporter_enabled: true
            prometheus_retention: 15d
          hosts:
            legion006:
              ansible_host: 192.168.1.36
            legion007:
              ansible_host: 192.168.1.37
            legion008:
              ansible_host: 192.168.1.38
            legion009:
              ansible_host: 192.168.1.39
            legion010:
              ansible_host: 192.168.1.40

        storage_nodes:
          vars:
            syncthing_enabled: true
            min_free_space: "2GB"
          hosts:
            legion011:
              ansible_host: 192.168.1.41
              storage_gb: 64
            legion012:
              ansible_host: 192.168.1.42
              storage_gb: 64
            legion013:
              ansible_host: 192.168.1.43
              storage_gb: 32
            legion014:
              ansible_host: 192.168.1.44
              storage_gb: 16

        edge_nodes:
          vars:
            traefik_enabled: true
            cloudflare_integration: true
          hosts:
            legion015:
              ansible_host: 192.168.1.45
            legion016:
              ansible_host: 192.168.1.46
            legion017:
              ansible_host: 192.168.1.47

        legion_cluster:
          vars:
            ansible_user: l3o
            # Pi specifications
            ram_mb: 1024
            min_storage_gb: 16
            max_storage_gb: 64
            cpu_cores: 4
          hosts:
            legion018:
              ansible_host: 192.168.1.48
            legion019:
              ansible_host: 192.168.1.49
            legion020:
              ansible_host: 192.168.1.50
            legion021:
              ansible_host: 192.168.1.51
            legion022:
              ansible_host: 192.168.1.52
            legion023:
              ansible_host: 192.168.1.53
            legion024:
              ansible_host: 192.168.1.54
            legion025:
              ansible_host: 192.168.1.55
            legion026:
              ansible_host: 192.168.1.56
            legion027:
              ansible_host: 192.168.1.57
            legion028:
              ansible_host: 192.168.1.58
            legion029:
              ansible_host: 192.168.1.59
            legion030:
              ansible_host: 192.168.1.60

        other_devices:
          hosts:
            raspberrypi:
              ansible_host: 192.168.1.181
              ansible_user: pi

    aws_integration:
      vars:
        route53_enabled: true
        aws_region: us-east-1
      children:
        primary_zone:
          hosts:
            alef:
              route53_role: primary
              domains:
                - name: homelab.internal
                  zone_id: "{{ aws_route53_zone_id }}"
        secondary_zones:
          hosts:
            legion001:
            legion015:
            legion016:
