---
all:
  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
    
    # Example structure for future expansion
    homeserver:
      hosts:
        homeserver01:
          ansible_host: 192.168.1.100  # Replace with actual IP
          
    # Add more host groups as needed
    # monitoring:
    #   hosts:
    #     monitor01:
    #       ansible_host: 192.168.1.101
