---
all:
  vars:
    ansible_user: l3o
    ansible_ssh_private_key_file: ~/.ssh/leo-personal

  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
    
    homelab:
      children:
        main_server:
          hosts:
            alef:
              ansible_host: 192.168.1.200
              ansible_port: 22
              # Server specifications
              ram_gb: 55
              storage_gb: 3000
              cpu_cores: 8
        
        # High-memory services (1GB+ RAM)
        high_memory_nodes:
          hosts:
            alef:
        
        # Storage-intensive services (100GB+ storage)
        storage_nodes:
          hosts:
            alef:
        
        # Distributed services across Pi cluster
        dns_nodes:
          hosts:
            legion001:
            legion002:
            legion003:
        
        monitoring_nodes:
          hosts:
            legion004:
            legion005:
            legion006:
        
        automation_nodes:
          hosts:
            legion007:
            legion008:
            legion009:
            legion010:
        
        # Rest of legion cluster for general purpose/failover
        legion_cluster:
          vars:
            ansible_user: l3o
            # Pi specifications
            ram_mb: 1024
            min_storage_gb: 16
            max_storage_gb: 64
            cpu_cores: 4
          hosts:
            legion011:
              ansible_host: 192.168.1.211
              storage_gb: 64
            legion012:
              ansible_host: 192.168.1.212
              storage_gb: 32
            legion013:
              ansible_host: 192.168.1.213
            legion014:
              ansible_host: 192.168.1.214
            legion015:
              ansible_host: 192.168.1.215
            legion016:
              ansible_host: 192.168.1.216
            legion019:
              ansible_host: 192.168.1.219
            legion020:
              ansible_host: 192.168.1.220
            legion021:
              ansible_host: 192.168.1.221
            legion022:
              ansible_host: 192.168.1.222
            legion024:
              ansible_host: 192.168.1.224
            legion028:
              ansible_host: 192.168.1.228
            legion029:
              ansible_host: 192.168.1.229
            legion031:
              ansible_host: 192.168.1.231
            legion034:
              ansible_host: 192.168.1.234
            legion035:
              ansible_host: 192.168.1.235
            legion036:
              ansible_host: 192.168.1.236
            legion037:
              ansible_host: 192.168.1.237
            legion038:
              ansible_host: 192.168.1.238
            legion040:
              ansible_host: 192.168.1.240

        other_devices:
          hosts:
            raspberrypi:
              ansible_host: 192.168.1.181
              ansible_user: pi
