---
- name: Delete NAT Gateway
  amazon.aws.ec2_vpc_nat_gateway:
    nat_gateway_id: "{{ nat_gateway.nat_gateway_id }}"
    state: absent
    region: "{{ aws_region }}"
    wait: yes
  when: nat_gateway is defined

- name: Release NAT Gateway EIP
  amazon.aws.ec2_eip:
    allocation_id: "{{ nat_eip.allocation_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: nat_eip is defined

- name: Terminate test instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ test_instance.instances[0].instance_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_instance is defined

- name: Delete security group
  amazon.aws.ec2_security_group:
    group_id: "{{ test_sg.group_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_sg is defined

- name: Delete route table
  amazon.aws.ec2_vpc_route_table:
    route_table_id: "{{ route_table.route_table.id }}"
    state: absent
    region: "{{ aws_region }}"
  when: route_table is defined

- name: Delete public subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ test_vpc.vpc.id }}"
    cidr: "{{ subnet_config.public.cidr }}"
    state: absent
    region: "{{ aws_region }}"
  when: public_subnet is defined

- name: Delete internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ test_vpc.vpc.id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_igw is defined

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    vpc_id: "{{ test_vpc.vpc.id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_vpc is defined
