---
- name: Terminate test instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ test_instance.instances[0].instance_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_instance is defined

- name: Delete security group
  amazon.aws.ec2_security_group:
    group_id: "{{ test_sg.group_id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_sg is defined

- name: Delete subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ test_vpc.vpc.id }}"
    cidr: "{{ aws_subnet_cidr }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_subnet is defined

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    vpc_id: "{{ test_vpc.vpc.id }}"
    state: absent
    region: "{{ aws_region }}"
  when: test_vpc is defined
