---
- name: Verify AWS credentials
  ansible.builtin.command: aws sts get-caller-identity
  environment:
    AWS_PROFILE: "{{ aws_profile }}"
  register: aws_creds_check
  changed_when: false
  failed_when: aws_creds_check.rc != 0

- name: Verify target environment requirements
  ansible.builtin.assert:
    that:
      - instance_type_map[target_env] is defined
      - instance_type_map[target_env].ram_gb is defined
      - instance_type_map[target_env].vcpus is defined
    msg: "Invalid target environment: {{ target_env }}"

- name: Check AWS service quotas
  amazon.aws.aws_service_quota_info:
    service_code: ec2
    quota_code: L-1216C47A  # Running On-Demand instances
    region: "{{ aws_region }}"
  register: quota_check 

- name: Verify SSH key exists
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key
  failed_when: not ssh_key.stat.exists

- name: Verify SSH public key exists
  ansible.builtin.stat:
    path: "{{ ssh_public_key_path }}"
  register: ssh_pub_key
  failed_when: not ssh_pub_key.stat.exists

- name: Import SSH key to AWS if not exists
  amazon.aws.ec2_key:
    name: "{{ ssh_key_name }}"
    key_material: "{{ lookup('file', ssh_public_key_path) }}"
    region: "{{ aws_region }}"
  register: aws_key
  when: ssh_pub_key.stat.exists 