---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-personal
      ansible.builtin.include_role:
        name: ansible-role-personal
      vars:
        git_user_name: "l3ocifer"
        git_user_email: "lpask001@gmail.com
