---
# AWS Test Runner Configuration

# AWS Configuration
aws_region: "us-east-1"
aws_profile: "default"
aws_vpc_cidr: "10.0.0.0/16"
aws_subnet_cidr: "10.0.1.0/24"

# Instance Configuration
instance_type_map:
  "raspberry_pi":  # Matches RPi 3B specs
    type: "t3.micro"
    ram_gb: 1
    vcpus: 1
  "desktop":  # Matches desktop server specs
    type: "t3.2xlarge"
    ram_gb: 32
    vcpus: 8

# Test Configuration
test_timeout_minutes: 30
cleanup_on_success: true
cleanup_on_failure: false  # Keep instance for debugging
parallel_tests: 1  # Number of simultaneous test instances

# Verification
verification_retries: 3
verification_delay: 30  # seconds between retries

# Target Environment
target_env: "{{ 'raspberry_pi' if ansible_memtotal_mb <= 1024 else 'desktop' }}"

# SSH Configuration
ssh_config:
  user: "l3o"
  key_name: "leo-personal"
  key_path: "~/.ssh/leo-personal"
  public_key_path: "~/.ssh/leo-personal.pub"
  options:
    ServerAliveInterval: 60
    ServerAliveCountMax: 30
    StrictHostKeyChecking: "ask"
    VerifyHostKeyDNS: "yes"
    ForwardAgent: "no"
    AddKeysToAgent: "yes"

# Additional Security
security_group_rules:
  - proto: tcp
    ports: 22
    cidr_ip: "{{ ansible_default_ipv4.address }}/32"
  - proto: tcp
    ports: 80
    cidr_ip: "0.0.0.0/0"
  - proto: tcp
    ports: 443
    cidr_ip: "0.0.0.0/0"

# VPC Configuration
vpc_config:
  name: "l3o-homelab-test"
  cidr: "10.0.0.0/16"
  enable_dns_hostnames: true
  enable_dns_support: true
  enable_ipv6: false
  tags:
    Environment: "test"
    Project: "homelab"
    AutoRemove: "yes"

# Enhanced Subnet Configuration
subnet_config:
  public_1:
    name: "l3o-homelab-test-public-1"
    cidr: "10.0.1.0/24"
    az: "{{ aws_region }}a"
    map_public_ip: true
    tags:
      Type: "Public"
      AutoRemove: "yes"
  public_2:
    name: "l3o-homelab-test-public-2"
    cidr: "10.0.2.0/24"
    az: "{{ aws_region }}b"
    map_public_ip: true
    tags:
      Type: "Public"
      AutoRemove: "yes"
  private_1:
    name: "l3o-homelab-test-private-1"
    cidr: "10.0.3.0/24"
    az: "{{ aws_region }}a"
    map_public_ip: false
    tags:
      Type: "Private"
      AutoRemove: "yes"
  private_2:
    name: "l3o-homelab-test-private-2"
    cidr: "10.0.4.0/24"
    az: "{{ aws_region }}b"
    map_public_ip: false
    tags:
      Type: "Private"
      AutoRemove: "yes"

# Static IP Assignments (matching homelab)
static_ip_map:
  alef:
    private_ip: "10.0.3.200"
    subnet: "private_1"
    type: "desktop"
  legion_nodes:
    start_ip: "10.0.3.201"  # Will increment for each node
    subnet: "private_1"
    type: "raspberry_pi"
    count: 30  # Maximum number of legion nodes

# NAT Gateway Configuration
nat_gateway_config:
  enabled: true
  name: "l3o-homelab-test-nat"
  subnet: "public_1"

# Security Configuration
security_groups:
  test_instances:
    name: "l3o-homelab-test-sg"
    description: "Security group for homelab test instances"
    rules:
      ingress:
        - proto: tcp
          ports: [22]
          cidr_ip: "{{ ansible_default_ipv4.address }}/32"
          description: "SSH access from controller"
        - proto: tcp
          ports: [80, 443]
          cidr_ip: "0.0.0.0/0"
          description: "Web access"
        - proto: all
          from_port: -1
          to_port: -1
          cidr_ip: "10.0.0.0/16"
          description: "All internal VPC traffic"
      egress:
        - proto: -1
          from_port: -1
          to_port: -1
          cidr_ip: "0.0.0.0/0"
          description: "Allow all outbound traffic"
