---
- name: Test AWS server provisioning
  hosts: localhost
  vars:
    target_env: "desktop"  # Can be "desktop" or "raspberry_pi"
    aws_region: "us-east-1"
    roles_to_test: []  # Empty since we're just testing infrastructure
    cleanup_on_failure: false  # Keep instance for debugging if setup fails

  pre_tasks:
    - name: Verify AWS credentials
      command: aws sts get-caller-identity
      changed_when: false
      register: aws_check
      failed_when: aws_check.rc != 0

  roles:
    - role: aws_test_runner

  post_tasks:
    - name: Verify server accessibility
      wait_for:
        host: "{{ test_instance.instances[0].public_ip_address }}"
        port: 22
        timeout: 300
      register: ssh_check

    - name: Display infrastructure test results
      debug:
        msg: |
          AWS Infrastructure Test Results:
          Instance Type: {{ selected_instance_type }}
          Instance IP: {{ test_instance.instances[0].public_ip_address }}
          VPC ID: {{ test_vpc.vpc.id }}
          Subnet ID: {{ test_subnet.subnet.id }}
          Security Group: {{ test_sg.group_id }}
          SSH Access: {{ ssh_check is success }}
      when: test_instance is defined 